ENABLED_LAGUAGES = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "JSON",
  "Markdown",
  "YAML",
  "XML",
  "PHP",
  "Ruby",
  "Python",
  "Bash",
  "C",
  "C++",
  "C#",
  "Java",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Dart",
  "SQL",
  "Dockerfile",
  "Haskell",
  "Lua",
  "Perl",
  "R",
  "Scala",
  "Scheme",
  "Clojure",
  "Elixir",
  "Erlang",
  "Julia",
  "OCaml",
  "Racket",
  "Vim",
  "Crystal",
  "Plain Text",
].sort

LANGUAGE_TO_EXTENSION = {
  "HTML"       => "html",
  "CSS"        => "css",
  "JavaScript" => "js",
  "TypeScript" => "ts",
  "JSON"       => "json",
  "Markdown"   => "md",
  "YAML"       => "yml",
  "XML"        => "xml",
  "PHP"        => "php",
  "Ruby"       => "rb",
  "Python"     => "py",
  "Bash"       => "sh",
  "C"          => "c",
  "C++"        => "cpp",
  "C#"         => "cs",
  "Java"       => "java",
  "Go"         => "go",
  "Rust"       => "rs",
  "Swift"      => "swift",
  "Kotlin"     => "kt",
  "Dart"       => "dart",
  "SQL"        => "sql",
  "Dockerfile" => "dockerfile",
  "Haskell"    => "hs",
  "Lua"        => "lua",
  "Perl"       => "pl",
  "R"          => "r",
  "Scala"      => "scala",
  "Scheme"     => "scm",
  "Clojure"    => "clj",
  "Elixir"     => "ex",
  "Erlang"     => "erl",
  "Julia"      => "jl",
  "OCaml"      => "ml",
  "Racket"     => "rkt",
  "Vim"        => "vim",
  "Crystal"    => "cr",
  "Plain Text" => "txt",
}
